### ISSUE TITLE
CertStream URLs File NOT Accessible

### ISSUE THREAD

**Issue by imethanlee** [lindsey98/Phishpedia#10]
Hi,

https://sites.google.com/view/phishpedia-site/complementary-experiment mentioned that 131562 Certstream URLs are provided in a google doc file but it looks like the corresponding part is not accessible. May I know how to access and download it?

![image](https://user-images.githubusercontent.com/36200682/187592146-f98f147d-7d4b-43fb-84b4-75bf48424464.png)

Thanks!

**Comment by lindsey98** [comment]
Hi, 
   I make it visible now. However, the URLs are very old (2 years ago). If you want to get fresh feed, you can check this https://github.com/CaliDog/certstream-python

**Comment by imethanlee** [comment]
Thanks

**Comment by imethanlee** [comment]
Are there any labels for these your collected CertStream URLs?

**Comment by lindsey98** [comment]
No we didn't label
