### ISSUE TITLE
About evaluating the Phishpedia model

### ISSUE THREAD

**Issue by Fujiaoji** [lindsey98/Phishpedia#12]
Hi, I would like to evaluate the Phishpedia model as a baseline in our dataset, do I need to train it on my dataset first? Or I can directly use the model you uploaded to evaluate the accuracy, etc. Thanks

**Comment by lindsey98** [comment]
Hi Fujiao,
   Yes, you can use the model directly. Thanks!

Best,
Ruofan

Fujiao Ji ***@***.***> 于2023年5月11日周四 02:29写道：

**Comment by Fujiaoji** [comment]
> Hi Fujiao, Yes, you can use the model directly. Thanks! Best, Ruofan Fujiao Ji ***@***.***> 于2023年5月11日周四 02:29写道：
> […](#)

Okay, thanks for telling me.
