### ISSUE TITLE
About the domain

### ISSUE THREAD

**Issue by Fujiaoji** [lindsey98/Phishpedia#16]
Hi,

Hope you doing well. 

I have run your code of phishpedia, but now I find that you have updated the code. 

When I check the "phishpedia_classifier_logo" function and run the code on some benign websites, I find that the "matched_domain" always not include ".com", ".cn", etc., while the "tldextract.extract(url).domain + '.' + tldextract.extract(url).suffix" include these information. So I am wondering if there is a bug or you also need to update the domain.pkl. I am not sure, just put forward my question. 

Besides, I want to make sure what I am understanding is right. For the "phishpedia_classifier_logo" function, if the predict target brand is not None and the domain in the maintained domain list, then it should be benign and the output pred_target is None rather than the real brand?

Thanks

Best

Fujiao

**Comment by lindsey98** [comment]
Hi fujiao,

Yes I tried to update the domain matching function to include
top-level-domain as well.
Can you try replacing the old domain.pkl with new one
https://drive.google.com/file/d/1nTIC6311dvdY4cGsrI4c3WMndSauuHSm/view?usp=sharing.
Thanks!

Best,
Ruofan

Fujiao Ji ***@***.***> 于2023年6月24日周六 04:31写道：

**Comment by Fujiaoji** [comment]
Oh, got it. Thanks

**Comment by lindsey98** [comment]
Hi Fujiao, 
sorry that I think the former one should be correct, I wrongly uploaded.

**Comment by lindsey98** [comment]
I changed it by checking "matched_domain" with "tldextract.extract(url).domain" only, thanks

**Comment by Fujiaoji** [comment]
Okay, got it. I would like to double check, the phishintention and phishpedia use the same maintained domain.pkl, is this right? Thanks

**Comment by lindsey98** [comment]
Hi Fujiao,
   Yes they are.

Fujiao Ji ***@***.***> 于2023年10月29日周日 04:42写道：

**Comment by Fujiaoji** [comment]
Okay. Helps me a lot. Thanks
