### ISSUE TITLE
Request pip list versions

### ISSUE THREAD

**Issue by ahjea** [lindsey98/Phishpedia#17]
Hello, I'm trying to run the test code.

But I got an error in torch library.
I set my virtual environment with python 3.8.17 / cuda 11.0 / cudnn 8.0.4.
The other programs were installed using "requirements.txt".

However, I got an error below : 
`Traceback (most recent call last):
  File "test.py", line 8, in <module>
    ELE_MODEL, SIAMESE_THRE, SIAMESE_MODEL, LOGO_FEATS, LOGO_FILES, DOMAIN_MAP_PATH = load_config(cfg_path)
  File "/home/iis/Phishpedia/phishpedia/phishpedia_config.py", line 23, in load_config
    ELE_MODEL = config_rcnn(ELE_CFG_PATH, ELE_WEIGHTS_PATH, conf_threshold=ELE_CONFIG_THRE)
  File "/home/iis/Phishpedia/phishpedia/src/detectron2_pedia/inference.py", line 56, in config_rcnn
    predictor = DefaultPredictor(cfg)
  File "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 155, in load
    checkpoint = self._load_file(path)
  File "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 88, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 252, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

I think this error came from version confliction.

My installed pip packages are the same with below:
`Package                 Version
----------------------- ------------------
absl-py                 1.4.0
advertorch              0.2.3
antlr4-python3-runtime  4.9.3
anyio                   4.0.0
appdirs                 1.4.4
black                   21.4b2
cachetools              5.3.1
certifi                 2023.7.22
cffi                    1.15.1
charset-normalizer      3.2.0
click                   8.1.7
cloudpickle             2.2.1
contourpy               1.1.0
cryptography            38.0.4
cycler                  0.11.0
detectron2              0.6+cu111
exceptiongroup          1.1.3
filelock                3.12.3
fonttools               4.42.1
future                  0.18.3
fvcore                  0.1.5.post20221221
google-auth             2.23.0
google-auth-oauthlib    1.0.0
grpcio                  1.58.0
gspread                 5.11.1
h11                     0.14.0
httpcore                0.17.3
httplib2                0.22.0
httpx                   0.24.1
hydra-core              1.3.2
idna                    3.4
importlib-metadata      6.8.0
importlib-resources     6.0.1
iopath                  0.1.9
joblib                  1.3.2
kiwisolver              1.4.5
lxml                    4.9.3
Markdown                3.4.4
MarkupSafe              2.1.3
matplotlib              3.7.3
mypy-extensions         1.0.0
numpy                   1.24.4
oauth2client            4.1.3
oauthlib                3.2.2
omegaconf               2.3.0
opencv-python           4.8.0.76
packaging               23.1
pandas                  2.0.3
pathlib                 1.0.1
pathspec                0.11.2
phishpedia              0.0.0
Pillow                  9.5.0
pip                     23.2.1
portalocker             2.7.0
protobuf                4.24.3
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pycocotools             2.0.7
pycparser               2.21
pydot                   1.4.2
pyparsing               3.1.1
python-dateutil         2.8.2
python-telegram-bot     20.5
pytz                    2023.3.post1
PyYAML                  6.0.1
regex                   2023.8.8
requests                2.31.0
requests-file           1.5.1
requests-oauthlib       1.3.1
rsa                     4.9
scikit-learn            1.3.0
scipy                   1.10.1
setuptools              68.2.2
six                     1.16.0
sniffio                 1.3.0
tabulate                0.9.0
tensorboard             2.14.0
tensorboard-data-server 0.7.1
termcolor               2.3.0
threadpoolctl           3.2.0
tldextract              3.5.0
toml                    0.10.2
torch                   1.9.0+cu111
torchsummary            1.5.1
torchvision             0.10.0+cu111
tqdm                    4.66.1
typing_extensions       4.7.1
tzdata                  2023.3
urllib3                 1.26.16
Werkzeug                2.3.7
wheel                   0.41.2
yacs                    0.1.8
zipp                    3.16.2`

Could you share your package versions? or Do you know what is the problem is it?

**Comment by lindsey98** [comment]
I am afraid that it is because of the Git Large File Storage limitations
for huggingface, that the models downloaded are incomplete.
Alternatively, you can directly download the models from here:
https://drive.google.com/drive/folders/1rCEqhu1CS8tphwDKoxsCRh5t1PXfSceH?usp=sharing

And you put those models into your package directory, in your case I think
it is "/home/iis/miniconda3/envs/myenv/lib/python3.8/site-
packages/phishpedia/src/".
I hope this would resolve the issue.

jemin ***@***.***> 于2023年9月13日周三 05:26写道：

**Comment by lindsey98** [comment]
Hi Jemin,
  Could you go to the directory /home/iis/miniconda3/envs/
myenv/lib/python3.8/site-packages/phishpedia/src/siamese_pedia/.
 And check whether this is a zip file called expand_targetlist.zip. If yes,
please unzip it in the same directory.
 Then /home/iis/miniconda3/envs/myenv/lib/python3.8/site-
packages/phishpedia/src/siamese_pedia/expand_targetlist should be there, it
should contain the 277 brands' logos.


jemin ***@***.***> 于2023年9月14日周四 02:28写道：

**Comment by ahjea** [comment]
Thanks It works :)

I did create a directory named "expand_targetlist" first, 
Then used command "unzip expand_targetlist.zip -d ./expand_targetlist"
After that, I tried to run test code successfully.

Thank you for your help and fast response!
