### ISSUE TITLE
Training problem on the siamese model

### ISSUE THREAD

**Issue by Fujiaoji** [lindsey98/Phishpedia#23]
Hi, Hope you doing well.

I have a question when retrain all the models. From my understanding, there should be 2 models, 1)  rcnn model and 2) the siamese model.
1) use the benign30k to train the layout classifier, get the rcnn model. 
2) for training siamese model, there are 2 steps: a) train on logo2k, and b) fine-tune on target list 277 brands.
2)-a) first use the logo2k to train, and get the bit.pth.tar, in this step, the parameters are [bit_pretrained_dir='.', dataset='logo_2k', logdir='log', model='BiT-M-R50x1', name='log_log', save=True, weights_path=None]. 
2)-b) After the former step, how can I use the obtained model to get the siamese model on the target list 277 brands? Can I just set the parameters as [bit_pretrained_dir='.', dataset='targetlist', logdir='log', model='BiT-M-R50x1', name='log_log', save=True, weights_path='log/log_log/bit.pth.tar']. when I set as this, I always get an error, says" size mismatch for module.head.conv.weight: copying a param with shape torch.Size([2340, 2048, 1, 1]) from checkpoint, the shape in current model is torch.Size([277, 2048, 1, 1]).".  So could you please tell me how to do the 2)-b)? 

I am confused about the file "train_siamese/bit_pytorch_train/train.py" when loading weights from line 205-228. If we have trained the 2)-a) on logo 2k and get the weights bit.pth.tar, then delete the "checkpoint['model']['module.head.conv.weight'], checkpoint['model']['module.head.conv.bias']", however, the next step of "try" then reload the initial one again... DO I miss something? Thanks.

If there is any issues in the process of training of my understanding, feel free to tell me. Thanks. Have a good day

Fujiao

**Comment by Fujiaoji** [comment]
Thanks for your quick reply. It works! Now I am testing if the trained model is correct on the dataset. You really did an excellent job on these 2 projects. Have a great day.

**Comment by nTjing** [comment]
> Thanks for your quick reply. It works! Now I am testing if the trained model is correct on the dataset. You really did an excellent job on these 2 projects. Have a great day.

Hi Fujiao, 
     Can you share "train_targets.txt"? I can't find it. Thanks!
