### ISSUE TITLE
About ".pkl" file in the Logo2K+ dataset

### ISSUE THREAD

**Issue by IzayoiAster** [lindsey98/Phishpedia#26]
in `siamese_retrain\bit_pytorch\train.py`：
```python
        valid_set = GetLoader(
            data_root="./datasets/logo2k/Logo-2K+",
            data_list="./datasets/logo2k/val.txt",
            label_dict="./datasets/logo2k/logo2k_labeldict.pkl",
            transform=val_tx,
        )
```
but I can't find any `.pkl` files in the [Logo2K+ dataset](https://github.com/msn199959/Logo-2k-plus-Dataset?tab=readme-ov-file) , do I need to generate `logo2k_labeldict.pkl` myself ?

**Comment by lindsey98** [comment]
Hi IzayoiAster,
  You can download the pickle file from here: https://drive.google.com/file/d/1adCjkccF2gpPvvbkBu3MUvEmfAVcNpOL/view?usp=sharing. It is a mapping from brand names to class ids.

**Comment by IzayoiAster** [comment]
Thanks !
Btw, is `BiT-M-R50x1.npz` or `resnetv2_rgb_new.pth.tar` the final Siamese logo matching model after pre-train and fine-tune? I trained an alternative layout detector and I want to combine the detector with Phishpedia's Siamese model.

**Comment by lindsey98** [comment]
Hi, 
  The resnetv2_rgb_new.pth.tar is the final model after fine-tuning. BiT-M-R50x1.npz is the original ResNet50 model released by Google (https://github.com/google-research/big_transfer), I think it is pre-trained on ImageNet for general image feature extraction purpose.
