### ISSUE TITLE
Run phishpedia.py error

### ISSUE THREAD

**Issue by j1ya-22** [lindsey98/Phishpedia#27]
![image](https://github.com/lindsey98/Phishpedia/assets/110608884/09c4c093-8b3c-456d-9416-3433cc3511c1)
Hello,I confronted an issue that I ran phishpedia.py but I was told "No module named 'detectron2.config'".Actually I can use python to import  detectron2.Moreover,I use "python -m pip install -e detectron2" to download detectron2 but also faced with other problems.
![image](https://github.com/lindsey98/Phishpedia/assets/110608884/dab892b5-33d9-4942-bb1e-d4ca4f0d5a30)
![image](https://github.com/lindsey98/Phishpedia/assets/110608884/7ea0c7e5-58eb-4d2e-9e53-9566f5a1a1d5)
![image](https://github.com/lindsey98/Phishpedia/assets/110608884/dab892b5-33d9-4942-bb1e-d4ca4f0d5a30)
I'm puzzled with it,and can you help me?

**Comment by lindsey98** [comment]
Hi,
  From the error message: You need to update Visual C++ Redistributable. Ensure your system has the latest Visual C++ Redistributable installed. You can download and install it from the official Microsoft website.
