### ISSUE TITLE
Optimization suggestion

### ISSUE THREAD

**Issue by tijmengit** [lindsey98/Phishpedia#3]
Sorry for not creating a pull request, but I believe I do have an optimization suggestion.
in file src/siamese_pedia/inference.py at line 98, the variable logo_feat_list is an array of float64 holding only bitvalues. 
by placing: 
```
    logo_feat_list = logo_feat_list.astype(np.uint8)
```
before line 98, the size of the array is reduced, without effect on performance.
logo_feat_list size = 50,200,712 -> 6,275,208 bytes

This will further improve the speed of your model.

**Comment by lindsey98** [comment]
Thanks! This is a valuable suggestion.
