### ISSUE TITLE
Step Relu

### ISSUE THREAD

**Issue by Fujiaoji** [lindsey98/Phishpedia#32]
Hi, hope you doing well.

When I read the paper, I find that there are Siamese and Siamese++ model with different lies on StepRelu. However, when I check the model, there is no stepreslu. I am wondering that,  is the step relu included in the training process? Or just use relu to train the classifier, when testing the siamese, then replace the relu with steprelu, like the results in Table 6. Thanks

**Comment by lindsey98** [comment]
Yes, the StepReLU function is not included during the training phase because it nullifies the gradients.
 It is applied only during test time.
