### ISSUE TITLE
training data is disabled 

### ISSUE THREAD

**Issue by imsupreme** [lindsey98/Phishpedia#6]
It seems like that the URL of faster-rcnn training data is out of work

**Comment by lindsey98** [comment]
Thanks! I have updated the readme.

**Comment by imethanlee** [comment]
The google drive link for 'Labelled Logo Dataset' seems not available. https://drive.google.com/file/d/1L3KSWEXcnWzYdJ4hPrNEUvC8jaaNOiBa/view?usp=sharing

**Comment by lindsey98** [comment]
Hi, can you try these links:
https://drive.google.com/file/d/1yORUeSrF5vGcgxYrsCoqXcpOUHt-iHq_/view?usp=sharing
https://drive.google.com/file/d/1bH3Yp6K1B37B_sS_MNMz7yvYcOhOu-J8/view?usp=sharing
https://drive.google.com/file/d/1u56I0IHBgM9glNJl2wcLfaihp1L_U7eD/view?usp=sharing
