### ISSUE TITLE
Otuput Files

### ISSUE THREAD

**Issue by imethanlee** [lindsey98/Phishpedia#8]
Hi,

I noticed that if I run the following command, the program will generate two files ('predict_intention.png' and 'predict.png') for each url. Could you please explain what these two files represent, respectively?
`python run.py --folder <folder you want to test e.g. phishpedia/datasets/test_sites> --results <where you want to save the results e.g. test.txt> --no_repeat`

Thanks.

**Comment by lindsey98** [comment]
predict_intention.png is the result from PhishIntention, 
predict.png is the result from Phishpedia
